server:
  api-prefix: /api

user-api/mp-rest/url: "http://localhost:5100"
forecast-provider-api/mp-rest/url: "http://localhost:5200"

quarkus:
  http:
    port: 5000
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://192.168.1.4:3307/weather_api
  hibernate-orm:
    database:
      generation: "drop-and-create"
