greeting:
  message: "hello"

user-api/mp-rest/url: "http://localhost:5100"
forecast-provider-api/mp-rest/url: "http://localhost:5200"

quarkus:
  http:
    test-port: 5003
  test:
    continuous-testing: enabled
  datasource:
    db-kind: h2
    username: sa
    password: root
    jdbc:
      url: jdbc:h2:mem:weather_api
  hibernate-orm:
    sql-load-script: no-file
    database:
      generation: "drop-and-create"
