version: '3.1'

services:

  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: dev_webchat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: webchat
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
