apiVersion: v1
kind: Pod
metadata:
  name: weather-api
  labels:
    app: quarkus-forcast
    api: quarkus-forcast-api
spec:
  containers:
    - name: forecast
      image: unipasssbackend/forecast:latest
      ports:
      - containerPort: 5000
        name: http
        protocol: TCP
      readinessProbe:
        httpGet:
          path: /q/health/ready
          port: 5000
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /q/health/live
          port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: forecast-service
  labels:
    tier: backend
    app: quarkus-forcast
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    api: quarkus-forcast-api


---
apiVersion: v1
kind: Pod
metadata:
  name: weather-api-provider
spec:
  containers:
    - name: forecast-provider
      image: unipasssbackend/forecast-provider:latest
      ports:
        - containerPort: 5200
          name: http
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /q/health/ready
          port: 5200
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /q/health/live
          port: 5200
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: weather_api
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql