greeting:
  message: "hello"
quarkus:
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3306/forecast_provider
  hibernate-orm:
    sql-load-script: no-file
    database:
      generation: "drop-and-create"
