greeting:
  message: "hello"


user-api/mp-rest/url: "http://users-service:5100"
forecast-provider-api/mp-rest/url: "http://forecast-pro-service:5200"
forecast-api/mp-rest/url: "http://forecast-service:5000"

quarkus:
  http:
    port: 5200
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://forecast-pro-db:3306/forecast_provider
  hibernate-orm:
    database:
      generation: "drop-and-create"
