greeting:
  message: "hello"


user-api/mp-rest/url: "http://localhost:5100"
forecast-provider-api/mp-rest/url: "http://localhost:5200"
forecast-api/mp-rest/url: "http://localhost:5000"

quarkus:
  http:
    port: 5200
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://:3306/forecast_provider
  hibernate-orm:
    sql-load-script: no-file
    database:
      generation: "drop-and-create"
