apiVersion: v1
kind: Service
metadata:
  name: forecast-pro-db
spec:
  ports:
    - port: 3306
  selector:
    app: forecast-pro-db
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-pro-db
spec:
  selector:
    matchLabels:
      app: forecast-pro-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: forecast-pro-db
    spec:
      containers:
        - image: mysql:5.6
          name: forecast-pro-db
          env:
            - name: MYSQL_DATABASE
              value: forecast_provider
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: forecast-pro-db