server:
  api-prefix: /api

user-api/mp-rest/url: "http://users-service:5100"
forecast-provider-api/mp-rest/url: "http://forecast-pro-service:5200"
forecast-api/mp-rest/url: "http://forecast-service:5000"

quarkus:
  http:
    port: 5100
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://users-db:3306/weather_api_user
  hibernate-orm:
    database:
      generation: "drop-and-create"
