server:
  api-prefix: /api


quarkus:
  http:
    port: 5100
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3307/weather_api_user
  hibernate-orm:
    database:
      generation: "drop-and-create"
