server:
  api-prefix: /api


forecast-api/mp-rest/url: "http://localhost:5000"
forecast-provider-api/mp-rest/url: "http://localhost:5200"

quarkus:
  http:
    port: 5100
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://users-db:3306/weather_api_user
  hibernate-orm:
    database:
      generation: "drop-and-create"
